github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-minimal
gfm_quirks: paragraph_end
calendar: "https://calendar.google.com/calendar/embed?title=Tapas%20y%20Chapas&amp;showTitle=0&amp;showPrint=0&amp;showTz=0&amp;mode=AGENDA&amp;height=600&amp;wkst=2&amp;hl=es&amp;bgcolor=%23FFFFFF&amp;src=a2h12mb7k23085elbocu5kpat8%40group.calendar.google.com&amp;color=%2328754E&amp;src=1kmvah96jn9lbjq4f7cjo3u4b8%40group.calendar.google.com&amp;color=%237A367A&amp;src=mlacksb0tlrkvh5k7lnf5u6p2o%40group.calendar.google.com&amp;color=%2329527A&amp;src=ls4anm48dpj0kforforn5b4lfs%40group.calendar.google.com&amp;color=%23A32929&amp;ctz=Europe%2FMadrid"
mail: "tapasychapas@gmail.com"
list: "tapasychapas@googlegroups.com"
icon: "favicon.png"
